---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
spec:
  channel: "stable"
  name: rhods-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

# oc-mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.20 --package nfd --v1
