---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
  upgradeStrategy: Default
