---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nfd
  namespace: openshift-nfd
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: nfd
  source: redhat-operators
  sourceNamespace: openshift-marketplace

# oc-mirror list operators --catalog registry.redhat.io/redhat/redhat-operator-index:v4.20 --package nfd --v1
