# Reference: https://instinct.docs.amd.com/projects/gpu-operator/en/latest/installation/openshift-olm.html#create-node-feature-discovery-rule
---
apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-nfd
spec:
  enableTaints: false
  instance: ""
  operand:
    servicePort: 0
  prunerOnDelete: false
  topologyUpdater: false
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist:
            - "0200"
            - "03"
            - "12"
          deviceLabelFields:
            - "vendor"
            - "device"
        custom:
        - name: amd-gpu
          labels:
            feature.node.kubernetes.io/amd-gpu: "true"
          matchAny:
            - matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    vendor: {op: In, value: ["1002"]}
                    device: {op: In, value: [
                      "75a3", # MI355X
                      "75a0", # MI350X
                      "74a5", # MI325X
                      "74a2", # MI308X
                      "74a8", # MI308X-HF
                      "74a0", # MI300A
                      "74a1", # MI300X
                      "74a9", # MI300X-HF
                      "74bd", # MI300X-HF
                      "740f", # MI210
                      "7408", # MI250X
                      "740c", # MI250/MI250X
                      "738c", # MI100
                      "738e"  # MI100
                    ]}
        - name: amd-vgpu
          labels:
            feature.node.kubernetes.io/amd-vgpu: "true"
          matchAny:
            - matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    vendor: {op: In, value: ["1002"]}
                    device: {op: In, value: [
                      "75b3", # MI355X VF
                      "75b0", # MI350X VF
                      "74b9", # MI325X VF
                      "74b6", # MI308X VF
                      "74bc", # MI308X-HF VF
                      "74b5", # MI300X VF
                      "74bd", # MI300X-HF VF
                      "7410", # MI210 VF
                    ]}

# oc get node -o yaml | grep "amd-gpu"
# oc get node -o yaml | grep "amd-vgpu"
